const teacher = [
  {
    id: "qe23r2323",
    firstName: "zakarah",
    lastName: "lakar",
    email: "zakarah.lakar@univ-constantine2.dz",
    phone: "0798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "lakar@500",
    department: "MI",
    module: "System Machine",
    status: "teacher", 
    groups: ["G1", "G2", "G3"],
    level: "Licence 1",
    sceance: ["TD"],
  },
  {
    id: "khdehwie34232",
    firstName: "nabil",
    lastName: "bilala",
    email: "nabil.bilala@univ-constantine2.dz",
    phone: "0798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "Nabil3000",
    department: "MI",
    module: "Networks Communucation",
    status: "Chelf Department",
    groups: ["G1", "G2", "G3", "G4"],
    level: "Licence 1",
    sceance: ["TD", "TP"],
  },
  {
    id: "nmbdu732u389r2",
    firstName: "nabil",
    lastName: "bilala",
    email: "mohammed.bilala@univ-constantine2.dz",
    phone: "0798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "Nabil3000",
    department: "TLSI",
    module: "Networks Communucation",
    status: "Chelf Department",
    groups: ["G1", "G2", "G3", "G4"],
    level: "Licence 1",
    sceance: ["TD"],
  },
  {
    id: "jdi237y2h2uh2",
    firstName: "nabil",
    lastName: "bilala",
    email: "musa.bilala@univ-constantine2.dz",
    phone: "0798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "Nabil3000",
    department: "TLSI",
    module: "Networks Communucation",
    status: "Chelf Department",
    groups: ["G1", "G2", "G3", "G4"],
    level: "Licence 1",
    sceance: ["TD", "TP"],
  },
  {
    id: "qekkjnie23823r2323",
    firstName: "nabil",
    lastName: "bilala",
    email: "moses.bilala@univ-constantine2.dz",
    phone: "0798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "Nabil3000",
    department: "IFA",
    module: "Networks Communucation",
    status: "Chelf Department",
    groups: ["G1", "G2", "G3", "G4"],
    level: "Licence 1",
    sceance: ["Tp"],
  },
  {
    id: "owi0232092",
    firstName: "nabil",
    lastName: "bilala",
    email: "mike.bilala@univ-constantine2.dz",
    phone: "0798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "Nabil3000",
    department: "IFA",
    module: "Networks Communucation",
    status: "Chelf Department",
    groups: ["G1", "G2", "G3", "G4"],
    level: "Licence 1",
    sceance: ["Tp"],
  },
  {
    id: "qe23r22jdhi2u3323",
    firstName: "nabil",
    lastName: "bilala",
    email: "mark.bilala@univ-constantine2.dz",
    phone: "0798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "Nabil3000",
    department: "MI",
    module: "Networks Communucation",
    status: "Chelf Department",
    groups: ["G1", "G2", "G3", "G4"],
    level: "Licence 1",
    sceance: ["Td"],
  },
  {
    id: "iweu9283iwu2",
    firstName: "nabil",
    lastName: "bilala",
    email: "emma.bilala@univ-constantine2.dz",
    phone: "0798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "Nabil3000",
    department: "MI",
    module: "Networks Communucation",
    status: "Chelf Department",
    groups: ["G1", "G2", "G3", "G4"],
    level: "Licence 1",
    sceance: ["Td"],
  },
  {
    id: "mso23e283902",
    firstName: "nabil",
    lastName: "bilala",
    email: "emmanuel.bilala@univ-constantine2.dz",
    phone: "0798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "Nabil3000",
    department: "TLSI",
    module: "Networks Communucation",
    status: "Chelf Department",
    groups: ["G1", "G2", "G3", "G4"],
    level: "Licence 1",
    sceance: ["Tp"],
  },
  {
    id: "nnqi3uy222222u2",
    firstName: "nabil",
    lastName: "bilala",
    email: "james.bilala@univ-constantine2.dz",
    phone: "0798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "Nabil3000",
    department: "TLSI",
    module: "Networks Communucation",
    status: "Chelf Department",
    groups: ["G1", "G2", "G3", "G4"],
    level: "Licence 1",
    sceance: ["Tp"],
  },
  {
    id: "kjni28892922",
    firstName: "nabil",
    lastName: "bilala",
    email: "pius.bilala@univ-constantine2.dz",
    phone: "0798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "Nabil3000",
    department: "IFA",
    module: "Networks Communucation",
    status: "Chelf Department",
    groups: ["G1", "G2", "G3", "G4"],
    level: "Licence 1",
    sceance: ["Td"],
  },
  {
    id: "kmdo2i3ru2d",
    firstName: "nabil",
    lastName: "bilala",
    email: "sunday.bilala@univ-constantine2.dz",
    phone: "0798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "Nabil3000",
    department: "IFA",
    module: "Networks Communucation",
    status: "Chelf Department",
    groups: ["G1", "G2", "G3", "G4"],
    level: "Licence 1",
    sceance: ["Td"],
  },
  {
    id: "qjhei23yd2",
    firstName: "nabil",
    lastName: "bilala",
    email: "bolu.bilala@univ-constantine2.dz",
    phone: "0798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "Nabil3000",
    department: "MI",
    module: "Networks Communucation",
    status: "Chelf Department",
    groups: ["G1", "G2", "G3", "G4"],
    level: "Licence 1",
    sceance: ["Tp"],
  },
  {
    id: "kqjd922jdx92",
    firstName: "nabil",
    lastName: "bilala",
    email: "david.bilala@univ-constantine2.dz",
    phone: "0798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "Nabil3000",
    department: "MI",
    module: "Networks Communucation",
    status: "Chelf Department",
    groups: ["G1", "G2", "G3", "G4"],
    level: "Licence 1",
    sceance: ["Tp"],
  },
  {
    id: "n23872dj23",
    firstName: "nabil",
    lastName: "bilala",
    email: "ama.bilala@univ-constantine2.dz",
    phone: "0798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "Nabil3000",
    department: "TLSI",
    module: "Networks Communucation",
    status: "Chelf Department",
    groups: ["G1", "G2", "G3", "G4"],
    level: "Licence 1",
    sceance: ["Td"],
  },
  {
    id: "kljqow9232",
    firstName: "nabil",
    lastName: "bilala",
    email: "issac.bilala@univ-constantine2.dz",
    phone: "0798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "Nabil3000",
    department: "TLSI",
    module: "Networks Communucation",
    status: "Chelf Department",
    groups: ["G1", "G2", "G3", "G4"],
    level: "Licence 1",
    sceance: ["Td"],
  },
  {
    id: "kn28329d2d",
    firstName: "nabil",
    lastName: "bilala",
    email: "lahhh.bilala@univ-constantine2.dz",
    phone: "0798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "Nabil3000",
    department: "IFA",
    module: "Networks Communucation",
    status: "Chelf Department",
    groups: ["G1", "G2", "G3", "G4"],
    level: "Licence 1",
    sceance: ["Tp"],
  },
  {
    id: "sn2i3yr2d2",
    firstName: "nabil",
    lastName: "bilala",
    email: "uthman.bilala@univ-constantine2.dz",
    phone: "0798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "Nabil3000",
    department: "IFA",
    module: "Networks Communucation",
    status: "Chelf Department",
    groups: ["G1", "G2", "G3", "G4"],
    level: "Licence 1",
    sceance: ["Tp"],
  },
  {
    id: "kjh92e2oi2u2",
    firstName: "nabil",
    lastName: "bilala",
    email: "muhsin.bilala@univ-constantine2.dz",
    phone: "0798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "Nabil3000",
    department: "MI",
    module: "Networks Communucation",
    status: "Chelf Department",
    groups: ["G1", "G2", "G3", "G4"],
    level: "Licence 1",
    sceance: ["Td"],
  },
  {
    id: " qwidu2dod2",
    firstName: "nabil",
    lastName: "bilala",
    email: "ibrahim.bilala@univ-constantine2.dz",
    phone: "0798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "Nabil3000",
    department: "MI",
    module: "Networks Communucation",
    status: "Chelf Department",
    groups: ["G1", "G2", "G3", "G4"],
    level: "Licence 1",
    sceance: ["Td"],
  },
  {
    id: "xiuf3odd",
    firstName: "nabil",
    lastName: "bilala",
    email: "adamu.bilala@univ-constantine2.dz",
    phone: "0798961871",
    address: "UV18 batiment oscar",
    city: "Constantine, nouvelle",
    password: "Nabil3000",
    department: "TLSI",
    module: "Networks Communucation",
    status: "Chelf Department",
    groups: ["G1", "G2", "G3", "G4"],
    level: "Licence 1",
    sceance: ["Tp"],
  },
];

module.exports = { teacher };
